// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: internal/infrastructure/config_loader/pb/conf.proto

package configpb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Observability *Observability         `protobuf:"bytes,3,opt,name=observability,proto3" json:"observability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_config_loader_pb_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetObservability() *Observability {
	if x != nil {
		return x.Observability
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *Server_GRPC           `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_config_loader_pb_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postgres      *Data_PostgreSQL       `protobuf:"bytes,1,opt,name=postgres,proto3" json:"postgres,omitempty"`
	GrpcClient    *Data_Client           `protobuf:"bytes,2,opt,name=grpc_client,json=grpcClient,proto3" json:"grpc_client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_config_loader_pb_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetPostgres() *Data_PostgreSQL {
	if x != nil {
		return x.Postgres
	}
	return nil
}

func (x *Data) GetGrpcClient() *Data_Client {
	if x != nil {
		return x.GrpcClient
	}
	return nil
}

type Observability struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GlobalAttributes map[string]string      `protobuf:"bytes,1,rep,name=global_attributes,json=globalAttributes,proto3" json:"global_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tracing          *Observability_Tracing `protobuf:"bytes,2,opt,name=tracing,proto3" json:"tracing,omitempty"`
	Metrics          *Observability_Metrics `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Observability) Reset() {
	*x = Observability{}
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_config_loader_pb_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Observability) GetGlobalAttributes() map[string]string {
	if x != nil {
		return x.GlobalAttributes
	}
	return nil
}

func (x *Observability) GetTracing() *Observability_Tracing {
	if x != nil {
		return x.Tracing
	}
	return nil
}

func (x *Observability) GetMetrics() *Observability_Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_config_loader_pb_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// PostgreSQL 数据库配置（Supabase 专用）
type Data_PostgreSQL struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DSN 连接串（必填）
	// 示例: postgresql://user:pass@host:5432/db?sslmode=require&search_path=myschema
	Dsn string `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	// 连接池配置
	MaxOpenConns      int32                `protobuf:"varint,2,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	MinOpenConns      int32                `protobuf:"varint,3,opt,name=min_open_conns,json=minOpenConns,proto3" json:"min_open_conns,omitempty"`
	MaxConnLifetime   *durationpb.Duration `protobuf:"bytes,4,opt,name=max_conn_lifetime,json=maxConnLifetime,proto3" json:"max_conn_lifetime,omitempty"`
	MaxConnIdleTime   *durationpb.Duration `protobuf:"bytes,5,opt,name=max_conn_idle_time,json=maxConnIdleTime,proto3" json:"max_conn_idle_time,omitempty"`
	HealthCheckPeriod *durationpb.Duration `protobuf:"bytes,6,opt,name=health_check_period,json=healthCheckPeriod,proto3" json:"health_check_period,omitempty"`
	// Supabase 特定配置
	Schema                   string `protobuf:"bytes,7,opt,name=schema,proto3" json:"schema,omitempty"`                                                                        // 默认 schema (如 "kratos_template")
	EnablePreparedStatements bool   `protobuf:"varint,8,opt,name=enable_prepared_statements,json=enablePreparedStatements,proto3" json:"enable_prepared_statements,omitempty"` // Pooler 模式建议设为 false
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Data_PostgreSQL) Reset() {
	*x = Data_PostgreSQL{}
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_PostgreSQL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_PostgreSQL) ProtoMessage() {}

func (x *Data_PostgreSQL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_PostgreSQL.ProtoReflect.Descriptor instead.
func (*Data_PostgreSQL) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_config_loader_pb_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_PostgreSQL) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data_PostgreSQL) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_PostgreSQL) GetMinOpenConns() int32 {
	if x != nil {
		return x.MinOpenConns
	}
	return 0
}

func (x *Data_PostgreSQL) GetMaxConnLifetime() *durationpb.Duration {
	if x != nil {
		return x.MaxConnLifetime
	}
	return nil
}

func (x *Data_PostgreSQL) GetMaxConnIdleTime() *durationpb.Duration {
	if x != nil {
		return x.MaxConnIdleTime
	}
	return nil
}

func (x *Data_PostgreSQL) GetHealthCheckPeriod() *durationpb.Duration {
	if x != nil {
		return x.HealthCheckPeriod
	}
	return nil
}

func (x *Data_PostgreSQL) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Data_PostgreSQL) GetEnablePreparedStatements() bool {
	if x != nil {
		return x.EnablePreparedStatements
	}
	return false
}

// gRPC Client 配置（可选，用于服务间调用）
type Data_Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // 目标地址，留空则不创建 client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Client) Reset() {
	*x = Data_Client{}
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Client) ProtoMessage() {}

func (x *Data_Client) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Client.ProtoReflect.Descriptor instead.
func (*Data_Client) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_config_loader_pb_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Client) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type Observability_Tracing struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enabled            bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Exporter           string                 `protobuf:"bytes,2,opt,name=exporter,proto3" json:"exporter,omitempty"`
	Endpoint           string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Headers            map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Insecure           bool                   `protobuf:"varint,5,opt,name=insecure,proto3" json:"insecure,omitempty"`
	SamplingRatio      float64                `protobuf:"fixed64,6,opt,name=sampling_ratio,json=samplingRatio,proto3" json:"sampling_ratio,omitempty"`
	BatchTimeout       *durationpb.Duration   `protobuf:"bytes,7,opt,name=batch_timeout,json=batchTimeout,proto3" json:"batch_timeout,omitempty"`
	ExportTimeout      *durationpb.Duration   `protobuf:"bytes,8,opt,name=export_timeout,json=exportTimeout,proto3" json:"export_timeout,omitempty"`
	MaxQueueSize       int32                  `protobuf:"varint,9,opt,name=max_queue_size,json=maxQueueSize,proto3" json:"max_queue_size,omitempty"`
	MaxExportBatchSize int32                  `protobuf:"varint,10,opt,name=max_export_batch_size,json=maxExportBatchSize,proto3" json:"max_export_batch_size,omitempty"`
	Required           bool                   `protobuf:"varint,11,opt,name=required,proto3" json:"required,omitempty"`
	ServiceName        string                 `protobuf:"bytes,12,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion     string                 `protobuf:"bytes,13,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	Environment        string                 `protobuf:"bytes,14,opt,name=environment,proto3" json:"environment,omitempty"`
	Attributes         map[string]string      `protobuf:"bytes,15,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Observability_Tracing) Reset() {
	*x = Observability_Tracing{}
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Tracing) ProtoMessage() {}

func (x *Observability_Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Tracing.ProtoReflect.Descriptor instead.
func (*Observability_Tracing) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_config_loader_pb_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Observability_Tracing) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Observability_Tracing) GetExporter() string {
	if x != nil {
		return x.Exporter
	}
	return ""
}

func (x *Observability_Tracing) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Tracing) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Observability_Tracing) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *Observability_Tracing) GetSamplingRatio() float64 {
	if x != nil {
		return x.SamplingRatio
	}
	return 0
}

func (x *Observability_Tracing) GetBatchTimeout() *durationpb.Duration {
	if x != nil {
		return x.BatchTimeout
	}
	return nil
}

func (x *Observability_Tracing) GetExportTimeout() *durationpb.Duration {
	if x != nil {
		return x.ExportTimeout
	}
	return nil
}

func (x *Observability_Tracing) GetMaxQueueSize() int32 {
	if x != nil {
		return x.MaxQueueSize
	}
	return 0
}

func (x *Observability_Tracing) GetMaxExportBatchSize() int32 {
	if x != nil {
		return x.MaxExportBatchSize
	}
	return 0
}

func (x *Observability_Tracing) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Observability_Tracing) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Observability_Tracing) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *Observability_Tracing) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Observability_Tracing) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Observability_Metrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Exporter            string                 `protobuf:"bytes,2,opt,name=exporter,proto3" json:"exporter,omitempty"`
	Endpoint            string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Headers             map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Insecure            bool                   `protobuf:"varint,5,opt,name=insecure,proto3" json:"insecure,omitempty"`
	Interval            *durationpb.Duration   `protobuf:"bytes,6,opt,name=interval,proto3" json:"interval,omitempty"`
	DisableRuntimeStats bool                   `protobuf:"varint,7,opt,name=disable_runtime_stats,json=disableRuntimeStats,proto3" json:"disable_runtime_stats,omitempty"`
	Required            bool                   `protobuf:"varint,8,opt,name=required,proto3" json:"required,omitempty"`
	ResourceAttributes  map[string]string      `protobuf:"bytes,9,rep,name=resource_attributes,json=resourceAttributes,proto3" json:"resource_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GrpcEnabled         *bool                  `protobuf:"varint,10,opt,name=grpc_enabled,json=grpcEnabled,proto3,oneof" json:"grpc_enabled,omitempty"`
	GrpcIncludeHealth   *bool                  `protobuf:"varint,11,opt,name=grpc_include_health,json=grpcIncludeHealth,proto3,oneof" json:"grpc_include_health,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Observability_Metrics) Reset() {
	*x = Observability_Metrics{}
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Metrics) ProtoMessage() {}

func (x *Observability_Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Metrics.ProtoReflect.Descriptor instead.
func (*Observability_Metrics) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_config_loader_pb_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Observability_Metrics) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Observability_Metrics) GetExporter() string {
	if x != nil {
		return x.Exporter
	}
	return ""
}

func (x *Observability_Metrics) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Metrics) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Observability_Metrics) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *Observability_Metrics) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *Observability_Metrics) GetDisableRuntimeStats() bool {
	if x != nil {
		return x.DisableRuntimeStats
	}
	return false
}

func (x *Observability_Metrics) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Observability_Metrics) GetResourceAttributes() map[string]string {
	if x != nil {
		return x.ResourceAttributes
	}
	return nil
}

func (x *Observability_Metrics) GetGrpcEnabled() bool {
	if x != nil && x.GrpcEnabled != nil {
		return *x.GrpcEnabled
	}
	return false
}

func (x *Observability_Metrics) GetGrpcIncludeHealth() bool {
	if x != nil && x.GrpcIncludeHealth != nil {
		return *x.GrpcIncludeHealth
	}
	return false
}

var File_internal_infrastructure_config_loader_pb_conf_proto protoreflect.FileDescriptor

const file_internal_infrastructure_config_loader_pb_conf_proto_rawDesc = "" +
	"\n" +
	"3internal/infrastructure/config_loader/pb/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\x1a\x17validate/validate.proto\"\x9e\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12?\n" +
	"\robservability\x18\x03 \x01(\v2\x19.kratos.api.ObservabilityR\robservability\"\xa0\x01\n" +
	"\x06Server\x12+\n" +
	"\x04grpc\x18\x01 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xf6\x04\n" +
	"\x04Data\x12A\n" +
	"\bpostgres\x18\x01 \x01(\v2\x1b.kratos.api.Data.PostgreSQLB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bpostgres\x128\n" +
	"\vgrpc_client\x18\x02 \x01(\v2\x17.kratos.api.Data.ClientR\n" +
	"grpcClient\x1a\xce\x03\n" +
	"\n" +
	"PostgreSQL\x12.\n" +
	"\x03dsn\x18\x01 \x01(\tB\x1c\xfaB\x19r\x17\x10\x012\x13^postgres(ql)?://.*R\x03dsn\x12/\n" +
	"\x0emax_open_conns\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01R\fmaxOpenConns\x12/\n" +
	"\x0emin_open_conns\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x04\x182(\x00R\fminOpenConns\x12E\n" +
	"\x11max_conn_lifetime\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0fmaxConnLifetime\x12F\n" +
	"\x12max_conn_idle_time\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x0fmaxConnIdleTime\x12I\n" +
	"\x13health_check_period\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x11healthCheckPeriod\x12\x16\n" +
	"\x06schema\x18\a \x01(\tR\x06schema\x12<\n" +
	"\x1aenable_prepared_statements\x18\b \x01(\bR\x18enablePreparedStatements\x1a \n" +
	"\x06Client\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"\x8a\x0e\n" +
	"\rObservability\x12\\\n" +
	"\x11global_attributes\x18\x01 \x03(\v2/.kratos.api.Observability.GlobalAttributesEntryR\x10globalAttributes\x12;\n" +
	"\atracing\x18\x02 \x01(\v2!.kratos.api.Observability.TracingR\atracing\x12;\n" +
	"\ametrics\x18\x03 \x01(\v2!.kratos.api.Observability.MetricsR\ametrics\x1a\x9b\x06\n" +
	"\aTracing\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bexporter\x18\x02 \x01(\tR\bexporter\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12H\n" +
	"\aheaders\x18\x04 \x03(\v2..kratos.api.Observability.Tracing.HeadersEntryR\aheaders\x12\x1a\n" +
	"\binsecure\x18\x05 \x01(\bR\binsecure\x12%\n" +
	"\x0esampling_ratio\x18\x06 \x01(\x01R\rsamplingRatio\x12>\n" +
	"\rbatch_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\fbatchTimeout\x12@\n" +
	"\x0eexport_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\rexportTimeout\x12$\n" +
	"\x0emax_queue_size\x18\t \x01(\x05R\fmaxQueueSize\x121\n" +
	"\x15max_export_batch_size\x18\n" +
	" \x01(\x05R\x12maxExportBatchSize\x12\x1a\n" +
	"\brequired\x18\v \x01(\bR\brequired\x12!\n" +
	"\fservice_name\x18\f \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\r \x01(\tR\x0eserviceVersion\x12 \n" +
	"\venvironment\x18\x0e \x01(\tR\venvironment\x12Q\n" +
	"\n" +
	"attributes\x18\x0f \x03(\v21.kratos.api.Observability.Tracing.AttributesEntryR\n" +
	"attributes\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xbd\x05\n" +
	"\aMetrics\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bexporter\x18\x02 \x01(\tR\bexporter\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12H\n" +
	"\aheaders\x18\x04 \x03(\v2..kratos.api.Observability.Metrics.HeadersEntryR\aheaders\x12\x1a\n" +
	"\binsecure\x18\x05 \x01(\bR\binsecure\x125\n" +
	"\binterval\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\binterval\x122\n" +
	"\x15disable_runtime_stats\x18\a \x01(\bR\x13disableRuntimeStats\x12\x1a\n" +
	"\brequired\x18\b \x01(\bR\brequired\x12j\n" +
	"\x13resource_attributes\x18\t \x03(\v29.kratos.api.Observability.Metrics.ResourceAttributesEntryR\x12resourceAttributes\x12&\n" +
	"\fgrpc_enabled\x18\n" +
	" \x01(\bH\x00R\vgrpcEnabled\x88\x01\x01\x123\n" +
	"\x13grpc_include_health\x18\v \x01(\bH\x01R\x11grpcIncludeHealth\x88\x01\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17ResourceAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_grpc_enabledB\x16\n" +
	"\x14_grpc_include_health\x1aC\n" +
	"\x15GlobalAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BZZXgithub.com/bionicotaku/kratos-template/internal/infrastructure/config_loader/pb;configpbb\x06proto3"

var (
	file_internal_infrastructure_config_loader_pb_conf_proto_rawDescOnce sync.Once
	file_internal_infrastructure_config_loader_pb_conf_proto_rawDescData []byte
)

func file_internal_infrastructure_config_loader_pb_conf_proto_rawDescGZIP() []byte {
	file_internal_infrastructure_config_loader_pb_conf_proto_rawDescOnce.Do(func() {
		file_internal_infrastructure_config_loader_pb_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infrastructure_config_loader_pb_conf_proto_rawDesc), len(file_internal_infrastructure_config_loader_pb_conf_proto_rawDesc)))
	})
	return file_internal_infrastructure_config_loader_pb_conf_proto_rawDescData
}

var file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_infrastructure_config_loader_pb_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),             // 0: kratos.api.Bootstrap
	(*Server)(nil),                // 1: kratos.api.Server
	(*Data)(nil),                  // 2: kratos.api.Data
	(*Observability)(nil),         // 3: kratos.api.Observability
	(*Server_GRPC)(nil),           // 4: kratos.api.Server.GRPC
	(*Data_PostgreSQL)(nil),       // 5: kratos.api.Data.PostgreSQL
	(*Data_Client)(nil),           // 6: kratos.api.Data.Client
	(*Observability_Tracing)(nil), // 7: kratos.api.Observability.Tracing
	(*Observability_Metrics)(nil), // 8: kratos.api.Observability.Metrics
	nil,                           // 9: kratos.api.Observability.GlobalAttributesEntry
	nil,                           // 10: kratos.api.Observability.Tracing.HeadersEntry
	nil,                           // 11: kratos.api.Observability.Tracing.AttributesEntry
	nil,                           // 12: kratos.api.Observability.Metrics.HeadersEntry
	nil,                           // 13: kratos.api.Observability.Metrics.ResourceAttributesEntry
	(*durationpb.Duration)(nil),   // 14: google.protobuf.Duration
}
var file_internal_infrastructure_config_loader_pb_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.observability:type_name -> kratos.api.Observability
	4,  // 3: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	5,  // 4: kratos.api.Data.postgres:type_name -> kratos.api.Data.PostgreSQL
	6,  // 5: kratos.api.Data.grpc_client:type_name -> kratos.api.Data.Client
	9,  // 6: kratos.api.Observability.global_attributes:type_name -> kratos.api.Observability.GlobalAttributesEntry
	7,  // 7: kratos.api.Observability.tracing:type_name -> kratos.api.Observability.Tracing
	8,  // 8: kratos.api.Observability.metrics:type_name -> kratos.api.Observability.Metrics
	14, // 9: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	14, // 10: kratos.api.Data.PostgreSQL.max_conn_lifetime:type_name -> google.protobuf.Duration
	14, // 11: kratos.api.Data.PostgreSQL.max_conn_idle_time:type_name -> google.protobuf.Duration
	14, // 12: kratos.api.Data.PostgreSQL.health_check_period:type_name -> google.protobuf.Duration
	10, // 13: kratos.api.Observability.Tracing.headers:type_name -> kratos.api.Observability.Tracing.HeadersEntry
	14, // 14: kratos.api.Observability.Tracing.batch_timeout:type_name -> google.protobuf.Duration
	14, // 15: kratos.api.Observability.Tracing.export_timeout:type_name -> google.protobuf.Duration
	11, // 16: kratos.api.Observability.Tracing.attributes:type_name -> kratos.api.Observability.Tracing.AttributesEntry
	12, // 17: kratos.api.Observability.Metrics.headers:type_name -> kratos.api.Observability.Metrics.HeadersEntry
	14, // 18: kratos.api.Observability.Metrics.interval:type_name -> google.protobuf.Duration
	13, // 19: kratos.api.Observability.Metrics.resource_attributes:type_name -> kratos.api.Observability.Metrics.ResourceAttributesEntry
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_config_loader_pb_conf_proto_init() }
func file_internal_infrastructure_config_loader_pb_conf_proto_init() {
	if File_internal_infrastructure_config_loader_pb_conf_proto != nil {
		return
	}
	file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infrastructure_config_loader_pb_conf_proto_rawDesc), len(file_internal_infrastructure_config_loader_pb_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_infrastructure_config_loader_pb_conf_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_config_loader_pb_conf_proto_depIdxs,
		MessageInfos:      file_internal_infrastructure_config_loader_pb_conf_proto_msgTypes,
	}.Build()
	File_internal_infrastructure_config_loader_pb_conf_proto = out.File
	file_internal_infrastructure_config_loader_pb_conf_proto_goTypes = nil
	file_internal_infrastructure_config_loader_pb_conf_proto_depIdxs = nil
}
