// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/video/v1/events.proto

package videov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType 定义事件类型枚举
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED   EventType = 0
	EventType_EVENT_TYPE_VIDEO_CREATED EventType = 1
	EventType_EVENT_TYPE_VIDEO_UPDATED EventType = 2
	EventType_EVENT_TYPE_VIDEO_DELETED EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_VIDEO_CREATED",
		2: "EVENT_TYPE_VIDEO_UPDATED",
		3: "EVENT_TYPE_VIDEO_DELETED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":   0,
		"EVENT_TYPE_VIDEO_CREATED": 1,
		"EVENT_TYPE_VIDEO_UPDATED": 2,
		"EVENT_TYPE_VIDEO_DELETED": 3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_video_v1_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_video_v1_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{0}
}

// VideoCreated 表示视频创建事件
// 当一个新视频元数据被创建时发布此事件
type VideoCreated struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	VideoId        string                  `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`                       // 视频唯一标识 (UUID)
	UploaderId     string                  `protobuf:"bytes,2,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`              // 上传者标识 (UUID)
	Title          string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                          // 视频标题
	Description    *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                              // 视频描述（可选）
	DurationMicros *wrapperspb.Int64Value  `protobuf:"bytes,5,opt,name=duration_micros,json=durationMicros,proto3" json:"duration_micros,omitempty"`  // 视频时长（微秒）
	PublishedAt    *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`           // 视频发布时间
	Version        int64                   `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`                                     // 聚合版本号
	OccurredAt     *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`              // 事件发生时间
	Status         string                  `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                                        // 视频状态
	MediaStatus    string                  `protobuf:"bytes,10,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`          // 媒体处理状态
	AnalysisStatus string                  `protobuf:"bytes,11,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"` // 分析状态
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoCreated) Reset() {
	*x = VideoCreated{}
	mi := &file_api_video_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCreated) ProtoMessage() {}

func (x *VideoCreated) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCreated.ProtoReflect.Descriptor instead.
func (*VideoCreated) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *VideoCreated) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoCreated) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *VideoCreated) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoCreated) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *VideoCreated) GetDurationMicros() *wrapperspb.Int64Value {
	if x != nil {
		return x.DurationMicros
	}
	return nil
}

func (x *VideoCreated) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *VideoCreated) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VideoCreated) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *VideoCreated) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoCreated) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *VideoCreated) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

// VideoUpdated 表示视频更新事件
// 当视频元数据被更新时发布此事件
// 只包含被更新的字段（部分更新语义）
type VideoUpdated struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	VideoId    string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`          // 视频唯一标识 (UUID)
	Version    int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                        // 新版本号
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // 事件发生时间
	// 以下字段为可选，仅包含实际被更新的字段
	Title             *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	Description       *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	DurationMicros    *wrapperspb.Int64Value  `protobuf:"bytes,12,opt,name=duration_micros,json=durationMicros,proto3" json:"duration_micros,omitempty"`
	Status            *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	MediaStatus       *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`
	AnalysisStatus    *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	ThumbnailUrl      *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	HlsMasterPlaylist *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=hls_master_playlist,json=hlsMasterPlaylist,proto3" json:"hls_master_playlist,omitempty"`
	Difficulty        *wrapperspb.StringValue `protobuf:"bytes,18,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Summary           *wrapperspb.StringValue `protobuf:"bytes,19,opt,name=summary,proto3" json:"summary,omitempty"`
	Tags              []string                `protobuf:"bytes,20,rep,name=tags,proto3" json:"tags,omitempty"`
	RawSubtitleUrl    *wrapperspb.StringValue `protobuf:"bytes,21,opt,name=raw_subtitle_url,json=rawSubtitleUrl,proto3" json:"raw_subtitle_url,omitempty"`
	PublishedAt       *timestamppb.Timestamp  `protobuf:"bytes,22,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VideoUpdated) Reset() {
	*x = VideoUpdated{}
	mi := &file_api_video_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoUpdated) ProtoMessage() {}

func (x *VideoUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoUpdated.ProtoReflect.Descriptor instead.
func (*VideoUpdated) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *VideoUpdated) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoUpdated) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VideoUpdated) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *VideoUpdated) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *VideoUpdated) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *VideoUpdated) GetDurationMicros() *wrapperspb.Int64Value {
	if x != nil {
		return x.DurationMicros
	}
	return nil
}

func (x *VideoUpdated) GetStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VideoUpdated) GetMediaStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.MediaStatus
	}
	return nil
}

func (x *VideoUpdated) GetAnalysisStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.AnalysisStatus
	}
	return nil
}

func (x *VideoUpdated) GetThumbnailUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.ThumbnailUrl
	}
	return nil
}

func (x *VideoUpdated) GetHlsMasterPlaylist() *wrapperspb.StringValue {
	if x != nil {
		return x.HlsMasterPlaylist
	}
	return nil
}

func (x *VideoUpdated) GetDifficulty() *wrapperspb.StringValue {
	if x != nil {
		return x.Difficulty
	}
	return nil
}

func (x *VideoUpdated) GetSummary() *wrapperspb.StringValue {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *VideoUpdated) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *VideoUpdated) GetRawSubtitleUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.RawSubtitleUrl
	}
	return nil
}

func (x *VideoUpdated) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// VideoDeleted 表示视频删除事件
// 当视频被删除时发布此事件
type VideoDeleted struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	VideoId       string                  `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`          // 视频唯一标识 (UUID)
	Version       int64                   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                        // 版本号
	DeletedAt     *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`    // 删除时间
	OccurredAt    *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // 事件发生时间
	Reason        *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                           // 删除原因（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoDeleted) Reset() {
	*x = VideoDeleted{}
	mi := &file_api_video_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoDeleted) ProtoMessage() {}

func (x *VideoDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoDeleted.ProtoReflect.Descriptor instead.
func (*VideoDeleted) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *VideoDeleted) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoDeleted) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VideoDeleted) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *VideoDeleted) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *VideoDeleted) GetReason() *wrapperspb.StringValue {
	if x != nil {
		return x.Reason
	}
	return nil
}

// Event 是通用事件信封（Envelope）
// 用于统一封装不同类型的事件，便于序列化、传输和处理
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                                // 事件唯一标识 (UUID)
	EventType     EventType              `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=video.v1.EventType" json:"event_type,omitempty"` // 事件类型
	AggregateId   string                 `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`                    // 聚合根 ID (通常是 video_id)
	AggregateType string                 `protobuf:"bytes,4,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`              // 聚合类型（如 "video"）
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`                                              // 聚合版本号
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`                       // 事件发生时间
	// 使用 oneof 实现多态，根据 event_type 包含对应的 payload
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Created
	//	*Event_Updated
	//	*Event_Deleted
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_video_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *Event) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *Event) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetCreated() *VideoCreated {
	if x != nil {
		if x, ok := x.Payload.(*Event_Created); ok {
			return x.Created
		}
	}
	return nil
}

func (x *Event) GetUpdated() *VideoUpdated {
	if x != nil {
		if x, ok := x.Payload.(*Event_Updated); ok {
			return x.Updated
		}
	}
	return nil
}

func (x *Event) GetDeleted() *VideoDeleted {
	if x != nil {
		if x, ok := x.Payload.(*Event_Deleted); ok {
			return x.Deleted
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Created struct {
	Created *VideoCreated `protobuf:"bytes,10,opt,name=created,proto3,oneof"`
}

type Event_Updated struct {
	Updated *VideoUpdated `protobuf:"bytes,11,opt,name=updated,proto3,oneof"`
}

type Event_Deleted struct {
	Deleted *VideoDeleted `protobuf:"bytes,12,opt,name=deleted,proto3,oneof"`
}

func (*Event_Created) isEvent_Payload() {}

func (*Event_Updated) isEvent_Payload() {}

func (*Event_Deleted) isEvent_Payload() {}

var File_api_video_v1_events_proto protoreflect.FileDescriptor

const file_api_video_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x19api/video/v1/events.proto\x12\bvideo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xe0\x03\n" +
	"\fVideoCreated\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1f\n" +
	"\vuploader_id\x18\x02 \x01(\tR\n" +
	"uploaderId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12D\n" +
	"\x0fduration_micros\x18\x05 \x01(\v2\x1b.google.protobuf.Int64ValueR\x0edurationMicros\x12=\n" +
	"\fpublished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\n" +
	" \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\v \x01(\tR\x0eanalysisStatus\"\x9a\a\n" +
	"\fVideoUpdated\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12;\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x122\n" +
	"\x05title\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\x05title\x12>\n" +
	"\vdescription\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12D\n" +
	"\x0fduration_micros\x18\f \x01(\v2\x1b.google.protobuf.Int64ValueR\x0edurationMicros\x124\n" +
	"\x06status\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\x06status\x12?\n" +
	"\fmedia_status\x18\x0e \x01(\v2\x1c.google.protobuf.StringValueR\vmediaStatus\x12E\n" +
	"\x0fanalysis_status\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\x0eanalysisStatus\x12A\n" +
	"\rthumbnail_url\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\fthumbnailUrl\x12L\n" +
	"\x13hls_master_playlist\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueR\x11hlsMasterPlaylist\x12<\n" +
	"\n" +
	"difficulty\x18\x12 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"difficulty\x126\n" +
	"\asummary\x18\x13 \x01(\v2\x1c.google.protobuf.StringValueR\asummary\x12\x12\n" +
	"\x04tags\x18\x14 \x03(\tR\x04tags\x12F\n" +
	"\x10raw_subtitle_url\x18\x15 \x01(\v2\x1c.google.protobuf.StringValueR\x0erawSubtitleUrl\x12=\n" +
	"\fpublished_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\"\xf1\x01\n" +
	"\fVideoDeleted\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x124\n" +
	"\x06reason\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x06reason\"\x9e\x03\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x122\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x13.video.v1.EventTypeR\teventType\x12!\n" +
	"\faggregate_id\x18\x03 \x01(\tR\vaggregateId\x12%\n" +
	"\x0eaggregate_type\x18\x04 \x01(\tR\raggregateType\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x122\n" +
	"\acreated\x18\n" +
	" \x01(\v2\x16.video.v1.VideoCreatedH\x00R\acreated\x122\n" +
	"\aupdated\x18\v \x01(\v2\x16.video.v1.VideoUpdatedH\x00R\aupdated\x122\n" +
	"\adeleted\x18\f \x01(\v2\x16.video.v1.VideoDeletedH\x00R\adeletedB\t\n" +
	"\apayload*\x81\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EVENT_TYPE_VIDEO_CREATED\x10\x01\x12\x1c\n" +
	"\x18EVENT_TYPE_VIDEO_UPDATED\x10\x02\x12\x1c\n" +
	"\x18EVENT_TYPE_VIDEO_DELETED\x10\x03B=Z;github.com/bionicotaku/kratos-template/api/video/v1;videov1b\x06proto3"

var (
	file_api_video_v1_events_proto_rawDescOnce sync.Once
	file_api_video_v1_events_proto_rawDescData []byte
)

func file_api_video_v1_events_proto_rawDescGZIP() []byte {
	file_api_video_v1_events_proto_rawDescOnce.Do(func() {
		file_api_video_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_video_v1_events_proto_rawDesc), len(file_api_video_v1_events_proto_rawDesc)))
	})
	return file_api_video_v1_events_proto_rawDescData
}

var file_api_video_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_video_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_video_v1_events_proto_goTypes = []any{
	(EventType)(0),                 // 0: video.v1.EventType
	(*VideoCreated)(nil),           // 1: video.v1.VideoCreated
	(*VideoUpdated)(nil),           // 2: video.v1.VideoUpdated
	(*VideoDeleted)(nil),           // 3: video.v1.VideoDeleted
	(*Event)(nil),                  // 4: video.v1.Event
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
	(*wrapperspb.Int64Value)(nil),  // 6: google.protobuf.Int64Value
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_api_video_v1_events_proto_depIdxs = []int32{
	5,  // 0: video.v1.VideoCreated.description:type_name -> google.protobuf.StringValue
	6,  // 1: video.v1.VideoCreated.duration_micros:type_name -> google.protobuf.Int64Value
	7,  // 2: video.v1.VideoCreated.published_at:type_name -> google.protobuf.Timestamp
	7,  // 3: video.v1.VideoCreated.occurred_at:type_name -> google.protobuf.Timestamp
	7,  // 4: video.v1.VideoUpdated.occurred_at:type_name -> google.protobuf.Timestamp
	5,  // 5: video.v1.VideoUpdated.title:type_name -> google.protobuf.StringValue
	5,  // 6: video.v1.VideoUpdated.description:type_name -> google.protobuf.StringValue
	6,  // 7: video.v1.VideoUpdated.duration_micros:type_name -> google.protobuf.Int64Value
	5,  // 8: video.v1.VideoUpdated.status:type_name -> google.protobuf.StringValue
	5,  // 9: video.v1.VideoUpdated.media_status:type_name -> google.protobuf.StringValue
	5,  // 10: video.v1.VideoUpdated.analysis_status:type_name -> google.protobuf.StringValue
	5,  // 11: video.v1.VideoUpdated.thumbnail_url:type_name -> google.protobuf.StringValue
	5,  // 12: video.v1.VideoUpdated.hls_master_playlist:type_name -> google.protobuf.StringValue
	5,  // 13: video.v1.VideoUpdated.difficulty:type_name -> google.protobuf.StringValue
	5,  // 14: video.v1.VideoUpdated.summary:type_name -> google.protobuf.StringValue
	5,  // 15: video.v1.VideoUpdated.raw_subtitle_url:type_name -> google.protobuf.StringValue
	7,  // 16: video.v1.VideoUpdated.published_at:type_name -> google.protobuf.Timestamp
	7,  // 17: video.v1.VideoDeleted.deleted_at:type_name -> google.protobuf.Timestamp
	7,  // 18: video.v1.VideoDeleted.occurred_at:type_name -> google.protobuf.Timestamp
	5,  // 19: video.v1.VideoDeleted.reason:type_name -> google.protobuf.StringValue
	0,  // 20: video.v1.Event.event_type:type_name -> video.v1.EventType
	7,  // 21: video.v1.Event.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 22: video.v1.Event.created:type_name -> video.v1.VideoCreated
	2,  // 23: video.v1.Event.updated:type_name -> video.v1.VideoUpdated
	3,  // 24: video.v1.Event.deleted:type_name -> video.v1.VideoDeleted
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_video_v1_events_proto_init() }
func file_api_video_v1_events_proto_init() {
	if File_api_video_v1_events_proto != nil {
		return
	}
	file_api_video_v1_events_proto_msgTypes[3].OneofWrappers = []any{
		(*Event_Created)(nil),
		(*Event_Updated)(nil),
		(*Event_Deleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_video_v1_events_proto_rawDesc), len(file_api_video_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_video_v1_events_proto_goTypes,
		DependencyIndexes: file_api_video_v1_events_proto_depIdxs,
		EnumInfos:         file_api_video_v1_events_proto_enumTypes,
		MessageInfos:      file_api_video_v1_events_proto_msgTypes,
	}.Build()
	File_api_video_v1_events_proto = out.File
	file_api_video_v1_events_proto_goTypes = nil
	file_api_video_v1_events_proto_depIdxs = nil
}
