// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/video/v1/query.proto

package videov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVideoDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoDetailRequest) Reset() {
	*x = GetVideoDetailRequest{}
	mi := &file_api_video_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoDetailRequest) ProtoMessage() {}

func (x *GetVideoDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoDetailRequest.ProtoReflect.Descriptor instead.
func (*GetVideoDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *GetVideoDetailRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetVideoDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *VideoDetail           `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoDetailResponse) Reset() {
	*x = GetVideoDetailResponse{}
	mi := &file_api_video_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoDetailResponse) ProtoMessage() {}

func (x *GetVideoDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoDetailResponse.ProtoReflect.Descriptor instead.
func (*GetVideoDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetVideoDetailResponse) GetDetail() *VideoDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type VideoDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	MediaStatus    string                 `protobuf:"bytes,4,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`
	AnalysisStatus string                 `protobuf:"bytes,5,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	HasLiked       bool                   `protobuf:"varint,8,opt,name=has_liked,json=hasLiked,proto3" json:"has_liked,omitempty"`
	HasBookmarked  bool                   `protobuf:"varint,9,opt,name=has_bookmarked,json=hasBookmarked,proto3" json:"has_bookmarked,omitempty"`
	HasWatched     bool                   `protobuf:"varint,10,opt,name=has_watched,json=hasWatched,proto3" json:"has_watched,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoDetail) Reset() {
	*x = VideoDetail{}
	mi := &file_api_video_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoDetail) ProtoMessage() {}

func (x *VideoDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoDetail.ProtoReflect.Descriptor instead.
func (*VideoDetail) Descriptor() ([]byte, []int) {
	return file_api_video_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *VideoDetail) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoDetail) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *VideoDetail) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *VideoDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *VideoDetail) GetHasLiked() bool {
	if x != nil {
		return x.HasLiked
	}
	return false
}

func (x *VideoDetail) GetHasBookmarked() bool {
	if x != nil {
		return x.HasBookmarked
	}
	return false
}

func (x *VideoDetail) GetHasWatched() bool {
	if x != nil {
		return x.HasWatched
	}
	return false
}

type ListUserPublicVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserPublicVideosRequest) Reset() {
	*x = ListUserPublicVideosRequest{}
	mi := &file_api_video_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserPublicVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserPublicVideosRequest) ProtoMessage() {}

func (x *ListUserPublicVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserPublicVideosRequest.ProtoReflect.Descriptor instead.
func (*ListUserPublicVideosRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserPublicVideosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserPublicVideosRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListUserPublicVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoListItem       `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserPublicVideosResponse) Reset() {
	*x = ListUserPublicVideosResponse{}
	mi := &file_api_video_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserPublicVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserPublicVideosResponse) ProtoMessage() {}

func (x *ListUserPublicVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserPublicVideosResponse.ProtoReflect.Descriptor instead.
func (*ListUserPublicVideosResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserPublicVideosResponse) GetVideos() []*VideoListItem {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListUserPublicVideosResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListMyUploadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	StatusFilter  []string               `protobuf:"bytes,3,rep,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyUploadsRequest) Reset() {
	*x = ListMyUploadsRequest{}
	mi := &file_api_video_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyUploadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyUploadsRequest) ProtoMessage() {}

func (x *ListMyUploadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyUploadsRequest.ProtoReflect.Descriptor instead.
func (*ListMyUploadsRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *ListMyUploadsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMyUploadsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListMyUploadsRequest) GetStatusFilter() []string {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

type ListMyUploadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*MyUploadListItem    `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyUploadsResponse) Reset() {
	*x = ListMyUploadsResponse{}
	mi := &file_api_video_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyUploadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyUploadsResponse) ProtoMessage() {}

func (x *ListMyUploadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyUploadsResponse.ProtoReflect.Descriptor instead.
func (*ListMyUploadsResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *ListMyUploadsResponse) GetVideos() []*MyUploadListItem {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListMyUploadsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type VideoListItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	MediaStatus    string                 `protobuf:"bytes,4,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`
	AnalysisStatus string                 `protobuf:"bytes,5,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoListItem) Reset() {
	*x = VideoListItem{}
	mi := &file_api_video_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoListItem) ProtoMessage() {}

func (x *VideoListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoListItem.ProtoReflect.Descriptor instead.
func (*VideoListItem) Descriptor() ([]byte, []int) {
	return file_api_video_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *VideoListItem) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoListItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoListItem) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *VideoListItem) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *VideoListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoListItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MyUploadListItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	MediaStatus    string                 `protobuf:"bytes,4,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`
	AnalysisStatus string                 `protobuf:"bytes,5,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	Version        int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MyUploadListItem) Reset() {
	*x = MyUploadListItem{}
	mi := &file_api_video_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyUploadListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyUploadListItem) ProtoMessage() {}

func (x *MyUploadListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyUploadListItem.ProtoReflect.Descriptor instead.
func (*MyUploadListItem) Descriptor() ([]byte, []int) {
	return file_api_video_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *MyUploadListItem) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *MyUploadListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MyUploadListItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MyUploadListItem) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *MyUploadListItem) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *MyUploadListItem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MyUploadListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MyUploadListItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_video_v1_query_proto protoreflect.FileDescriptor

const file_api_video_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x18api/video/v1/query.proto\x12\bvideo.v1\x1a\x1bbuf/validate/validate.proto\"<\n" +
	"\x15GetVideoDetailRequest\x12#\n" +
	"\bvideo_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\avideoId\"G\n" +
	"\x16GetVideoDetailResponse\x12-\n" +
	"\x06detail\x18\x01 \x01(\v2\x15.video.v1.VideoDetailR\x06detail\"\xc5\x02\n" +
	"\vVideoDetail\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\x04 \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\x05 \x01(\tR\x0eanalysisStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\thas_liked\x18\b \x01(\bR\bhasLiked\x12%\n" +
	"\x0ehas_bookmarked\x18\t \x01(\bR\rhasBookmarked\x12\x1f\n" +
	"\vhas_watched\x18\n" +
	" \x01(\bR\n" +
	"hasWatched\"Y\n" +
	"\x1bListUserPublicVideosRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"w\n" +
	"\x1cListUserPublicVideosResponse\x12/\n" +
	"\x06videos\x18\x01 \x03(\v2\x17.video.v1.VideoListItemR\x06videos\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"w\n" +
	"\x14ListMyUploadsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12#\n" +
	"\rstatus_filter\x18\x03 \x03(\tR\fstatusFilter\"s\n" +
	"\x15ListMyUploadsResponse\x122\n" +
	"\x06videos\x18\x01 \x03(\v2\x1a.video.v1.MyUploadListItemR\x06videos\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xe2\x01\n" +
	"\rVideoListItem\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\x04 \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\x05 \x01(\tR\x0eanalysisStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xff\x01\n" +
	"\x10MyUploadListItem\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\x04 \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\x05 \x01(\tR\x0eanalysisStatus\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt2\xa3\x02\n" +
	"\x13CatalogQueryService\x12S\n" +
	"\x0eGetVideoDetail\x12\x1f.video.v1.GetVideoDetailRequest\x1a .video.v1.GetVideoDetailResponse\x12e\n" +
	"\x14ListUserPublicVideos\x12%.video.v1.ListUserPublicVideosRequest\x1a&.video.v1.ListUserPublicVideosResponse\x12P\n" +
	"\rListMyUploads\x12\x1e.video.v1.ListMyUploadsRequest\x1a\x1f.video.v1.ListMyUploadsResponseBDZBgithub.com/bionicotaku/lingo-services-catalog/api/video/v1;videov1b\x06proto3"

var (
	file_api_video_v1_query_proto_rawDescOnce sync.Once
	file_api_video_v1_query_proto_rawDescData []byte
)

func file_api_video_v1_query_proto_rawDescGZIP() []byte {
	file_api_video_v1_query_proto_rawDescOnce.Do(func() {
		file_api_video_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_video_v1_query_proto_rawDesc), len(file_api_video_v1_query_proto_rawDesc)))
	})
	return file_api_video_v1_query_proto_rawDescData
}

var file_api_video_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_video_v1_query_proto_goTypes = []any{
	(*GetVideoDetailRequest)(nil),        // 0: video.v1.GetVideoDetailRequest
	(*GetVideoDetailResponse)(nil),       // 1: video.v1.GetVideoDetailResponse
	(*VideoDetail)(nil),                  // 2: video.v1.VideoDetail
	(*ListUserPublicVideosRequest)(nil),  // 3: video.v1.ListUserPublicVideosRequest
	(*ListUserPublicVideosResponse)(nil), // 4: video.v1.ListUserPublicVideosResponse
	(*ListMyUploadsRequest)(nil),         // 5: video.v1.ListMyUploadsRequest
	(*ListMyUploadsResponse)(nil),        // 6: video.v1.ListMyUploadsResponse
	(*VideoListItem)(nil),                // 7: video.v1.VideoListItem
	(*MyUploadListItem)(nil),             // 8: video.v1.MyUploadListItem
}
var file_api_video_v1_query_proto_depIdxs = []int32{
	2, // 0: video.v1.GetVideoDetailResponse.detail:type_name -> video.v1.VideoDetail
	7, // 1: video.v1.ListUserPublicVideosResponse.videos:type_name -> video.v1.VideoListItem
	8, // 2: video.v1.ListMyUploadsResponse.videos:type_name -> video.v1.MyUploadListItem
	0, // 3: video.v1.CatalogQueryService.GetVideoDetail:input_type -> video.v1.GetVideoDetailRequest
	3, // 4: video.v1.CatalogQueryService.ListUserPublicVideos:input_type -> video.v1.ListUserPublicVideosRequest
	5, // 5: video.v1.CatalogQueryService.ListMyUploads:input_type -> video.v1.ListMyUploadsRequest
	1, // 6: video.v1.CatalogQueryService.GetVideoDetail:output_type -> video.v1.GetVideoDetailResponse
	4, // 7: video.v1.CatalogQueryService.ListUserPublicVideos:output_type -> video.v1.ListUserPublicVideosResponse
	6, // 8: video.v1.CatalogQueryService.ListMyUploads:output_type -> video.v1.ListMyUploadsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_video_v1_query_proto_init() }
func file_api_video_v1_query_proto_init() {
	if File_api_video_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_video_v1_query_proto_rawDesc), len(file_api_video_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_video_v1_query_proto_goTypes,
		DependencyIndexes: file_api_video_v1_query_proto_depIdxs,
		MessageInfos:      file_api_video_v1_query_proto_msgTypes,
	}.Build()
	File_api_video_v1_query_proto = out.File
	file_api_video_v1_query_proto_goTypes = nil
	file_api_video_v1_query_proto_depIdxs = nil
}
