// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/video/v1/upload.proto

package videov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InitResumableUploadRequest 描述移动端在上传前上报的元数据。
type InitResumableUploadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SizeBytes       int64                  `protobuf:"varint,1,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType     string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ContentMd5Hex   string                 `protobuf:"bytes,3,opt,name=content_md5_hex,json=contentMd5Hex,proto3" json:"content_md5_hex,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Title           string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitResumableUploadRequest) Reset() {
	*x = InitResumableUploadRequest{}
	mi := &file_api_video_v1_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResumableUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResumableUploadRequest) ProtoMessage() {}

func (x *InitResumableUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResumableUploadRequest.ProtoReflect.Descriptor instead.
func (*InitResumableUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_upload_proto_rawDescGZIP(), []int{0}
}

func (x *InitResumableUploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *InitResumableUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InitResumableUploadRequest) GetContentMd5Hex() string {
	if x != nil {
		return x.ContentMd5Hex
	}
	return ""
}

func (x *InitResumableUploadRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *InitResumableUploadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InitResumableUploadRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// InitResumableUploadResponse 返回预留的视频标识与会话初始化 URL。
type InitResumableUploadResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VideoId          string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ResumableInitUrl string                 `protobuf:"bytes,2,opt,name=resumable_init_url,json=resumableInitUrl,proto3" json:"resumable_init_url,omitempty"`
	ExpiresAtUnixms  int64                  `protobuf:"varint,3,opt,name=expires_at_unixms,json=expiresAtUnixms,proto3" json:"expires_at_unixms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InitResumableUploadResponse) Reset() {
	*x = InitResumableUploadResponse{}
	mi := &file_api_video_v1_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResumableUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResumableUploadResponse) ProtoMessage() {}

func (x *InitResumableUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResumableUploadResponse.ProtoReflect.Descriptor instead.
func (*InitResumableUploadResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_upload_proto_rawDescGZIP(), []int{1}
}

func (x *InitResumableUploadResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *InitResumableUploadResponse) GetResumableInitUrl() string {
	if x != nil {
		return x.ResumableInitUrl
	}
	return ""
}

func (x *InitResumableUploadResponse) GetExpiresAtUnixms() int64 {
	if x != nil {
		return x.ExpiresAtUnixms
	}
	return 0
}

var File_api_video_v1_upload_proto protoreflect.FileDescriptor

const file_api_video_v1_upload_proto_rawDesc = "" +
	"\n" +
	"\x19api/video/v1/upload.proto\x12\bvideo.v1\x1a\x1bbuf/validate/validate.proto\"\xb6\x02\n" +
	"\x1aInitResumableUploadRequest\x12&\n" +
	"\n" +
	"size_bytes\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\tsizeBytes\x12*\n" +
	"\fcontent_type\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vcontentType\x12C\n" +
	"\x0fcontent_md5_hex\x18\x03 \x01(\tB\x1b\xbaH\x18r\x162\x11^[a-fA-F0-9]{32}$\x98\x01 R\rcontentMd5Hex\x125\n" +
	"\x10duration_seconds\x18\x04 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xac\x02(\x01R\x0fdurationSeconds\x12\x1d\n" +
	"\x05title\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x12)\n" +
	"\vdescription\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdescription\"\xae\x01\n" +
	"\x1bInitResumableUploadResponse\x12#\n" +
	"\bvideo_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\avideoId\x125\n" +
	"\x12resumable_init_url\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x10resumableInitUrl\x123\n" +
	"\x11expires_at_unixms\x18\x03 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x0fexpiresAtUnixms2s\n" +
	"\rUploadService\x12b\n" +
	"\x13InitResumableUpload\x12$.video.v1.InitResumableUploadRequest\x1a%.video.v1.InitResumableUploadResponseBDZBgithub.com/bionicotaku/lingo-services-catalog/api/video/v1;videov1b\x06proto3"

var (
	file_api_video_v1_upload_proto_rawDescOnce sync.Once
	file_api_video_v1_upload_proto_rawDescData []byte
)

func file_api_video_v1_upload_proto_rawDescGZIP() []byte {
	file_api_video_v1_upload_proto_rawDescOnce.Do(func() {
		file_api_video_v1_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_video_v1_upload_proto_rawDesc), len(file_api_video_v1_upload_proto_rawDesc)))
	})
	return file_api_video_v1_upload_proto_rawDescData
}

var file_api_video_v1_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_video_v1_upload_proto_goTypes = []any{
	(*InitResumableUploadRequest)(nil),  // 0: video.v1.InitResumableUploadRequest
	(*InitResumableUploadResponse)(nil), // 1: video.v1.InitResumableUploadResponse
}
var file_api_video_v1_upload_proto_depIdxs = []int32{
	0, // 0: video.v1.UploadService.InitResumableUpload:input_type -> video.v1.InitResumableUploadRequest
	1, // 1: video.v1.UploadService.InitResumableUpload:output_type -> video.v1.InitResumableUploadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_video_v1_upload_proto_init() }
func file_api_video_v1_upload_proto_init() {
	if File_api_video_v1_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_video_v1_upload_proto_rawDesc), len(file_api_video_v1_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_video_v1_upload_proto_goTypes,
		DependencyIndexes: file_api_video_v1_upload_proto_depIdxs,
		MessageInfos:      file_api_video_v1_upload_proto_msgTypes,
	}.Build()
	File_api_video_v1_upload_proto = out.File
	file_api_video_v1_upload_proto_goTypes = nil
	file_api_video_v1_upload_proto_depIdxs = nil
}
