// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/video/v1/video.proto

package videov1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetVideoDetailRequest 表示查询参数。
type GetVideoDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // UUID 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoDetailRequest) Reset() {
	*x = GetVideoDetailRequest{}
	mi := &file_api_video_v1_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoDetailRequest) ProtoMessage() {}

func (x *GetVideoDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoDetailRequest.ProtoReflect.Descriptor instead.
func (*GetVideoDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{0}
}

func (x *GetVideoDetailRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

// GetVideoDetailResponse 封装查询结果。
type GetVideoDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *VideoDetail           `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoDetailResponse) Reset() {
	*x = GetVideoDetailResponse{}
	mi := &file_api_video_v1_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoDetailResponse) ProtoMessage() {}

func (x *GetVideoDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoDetailResponse.ProtoReflect.Descriptor instead.
func (*GetVideoDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{1}
}

func (x *GetVideoDetailResponse) GetDetail() *VideoDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

// VideoDetail 只读视图，仅包含 ready/published 状态视频的核心字段。
// 数据来源：catalog.video_projection 表
type VideoDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`                      // 视频 ID
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                         // 标题
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                       // 状态（ready/published）
	MediaStatus    string                 `protobuf:"bytes,4,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`          // 媒体处理状态
	AnalysisStatus string                 `protobuf:"bytes,5,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"` // AI 分析状态
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                // 创建时间（UTC RFC3339）
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                // 更新时间（UTC RFC3339）
	HasLiked       bool                   `protobuf:"varint,8,opt,name=has_liked,json=hasLiked,proto3" json:"has_liked,omitempty"`                  // 是否点赞
	HasBookmarked  bool                   `protobuf:"varint,9,opt,name=has_bookmarked,json=hasBookmarked,proto3" json:"has_bookmarked,omitempty"`   // 是否收藏
	HasWatched     bool                   `protobuf:"varint,10,opt,name=has_watched,json=hasWatched,proto3" json:"has_watched,omitempty"`           // 是否观看
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoDetail) Reset() {
	*x = VideoDetail{}
	mi := &file_api_video_v1_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoDetail) ProtoMessage() {}

func (x *VideoDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoDetail.ProtoReflect.Descriptor instead.
func (*VideoDetail) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{2}
}

func (x *VideoDetail) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoDetail) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *VideoDetail) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *VideoDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *VideoDetail) GetHasLiked() bool {
	if x != nil {
		return x.HasLiked
	}
	return false
}

func (x *VideoDetail) GetHasBookmarked() bool {
	if x != nil {
		return x.HasBookmarked
	}
	return false
}

func (x *VideoDetail) GetHasWatched() bool {
	if x != nil {
		return x.HasWatched
	}
	return false
}

type ListUserPublicVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 每页数量（默认 20，最大 100）
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // 游标分页 token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserPublicVideosRequest) Reset() {
	*x = ListUserPublicVideosRequest{}
	mi := &file_api_video_v1_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserPublicVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserPublicVideosRequest) ProtoMessage() {}

func (x *ListUserPublicVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserPublicVideosRequest.ProtoReflect.Descriptor instead.
func (*ListUserPublicVideosRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserPublicVideosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserPublicVideosRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListUserPublicVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoListItem       `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`                                      // 视频列表
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 下页游标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserPublicVideosResponse) Reset() {
	*x = ListUserPublicVideosResponse{}
	mi := &file_api_video_v1_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserPublicVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserPublicVideosResponse) ProtoMessage() {}

func (x *ListUserPublicVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserPublicVideosResponse.ProtoReflect.Descriptor instead.
func (*ListUserPublicVideosResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserPublicVideosResponse) GetVideos() []*VideoListItem {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListUserPublicVideosResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListMyUploadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`            // 每页数量
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`          // 游标
	StatusFilter  []string               `protobuf:"bytes,3,rep,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // 可选状态过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyUploadsRequest) Reset() {
	*x = ListMyUploadsRequest{}
	mi := &file_api_video_v1_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyUploadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyUploadsRequest) ProtoMessage() {}

func (x *ListMyUploadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyUploadsRequest.ProtoReflect.Descriptor instead.
func (*ListMyUploadsRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{5}
}

func (x *ListMyUploadsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMyUploadsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListMyUploadsRequest) GetStatusFilter() []string {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

type ListMyUploadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*MyUploadListItem    `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`                                      // 我的上传列表
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 下页游标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyUploadsResponse) Reset() {
	*x = ListMyUploadsResponse{}
	mi := &file_api_video_v1_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyUploadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyUploadsResponse) ProtoMessage() {}

func (x *ListMyUploadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyUploadsResponse.ProtoReflect.Descriptor instead.
func (*ListMyUploadsResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{6}
}

func (x *ListMyUploadsResponse) GetVideos() []*MyUploadListItem {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListMyUploadsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type VideoListItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	MediaStatus    string                 `protobuf:"bytes,4,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`
	AnalysisStatus string                 `protobuf:"bytes,5,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoListItem) Reset() {
	*x = VideoListItem{}
	mi := &file_api_video_v1_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoListItem) ProtoMessage() {}

func (x *VideoListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoListItem.ProtoReflect.Descriptor instead.
func (*VideoListItem) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{7}
}

func (x *VideoListItem) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoListItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoListItem) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *VideoListItem) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *VideoListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoListItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MyUploadListItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	MediaStatus    string                 `protobuf:"bytes,4,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`
	AnalysisStatus string                 `protobuf:"bytes,5,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	Version        int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MyUploadListItem) Reset() {
	*x = MyUploadListItem{}
	mi := &file_api_video_v1_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyUploadListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyUploadListItem) ProtoMessage() {}

func (x *MyUploadListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyUploadListItem.ProtoReflect.Descriptor instead.
func (*MyUploadListItem) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{8}
}

func (x *MyUploadListItem) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *MyUploadListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MyUploadListItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MyUploadListItem) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *MyUploadListItem) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *MyUploadListItem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MyUploadListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MyUploadListItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// CreateVideoRequest 表示创建视频的请求参数。
// video_id 由数据库自动生成，不允许客户端指定
type CreateVideoRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UploadUserId     string                 `protobuf:"bytes,1,opt,name=upload_user_id,json=uploadUserId,proto3" json:"upload_user_id,omitempty"`             // 上传者 ID (UUID)
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                                 // 标题
	Description      *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`                               // 描述 (可选)
	RawFileReference string                 `protobuf:"bytes,4,opt,name=raw_file_reference,json=rawFileReference,proto3" json:"raw_file_reference,omitempty"` // 原始文件引用 (GCS 路径)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateVideoRequest) Reset() {
	*x = CreateVideoRequest{}
	mi := &file_api_video_v1_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoRequest) ProtoMessage() {}

func (x *CreateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVideoRequest) GetUploadUserId() string {
	if x != nil {
		return x.UploadUserId
	}
	return ""
}

func (x *CreateVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVideoRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateVideoRequest) GetRawFileReference() string {
	if x != nil {
		return x.RawFileReference
	}
	return ""
}

// CreateVideoResponse 表示创建视频的响应。
type CreateVideoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`                      // 创建的视频 ID
	CreatedAt      string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                // 创建时间（UTC RFC3339）
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                       // 视频状态
	MediaStatus    string                 `protobuf:"bytes,4,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`          // 媒体处理状态
	AnalysisStatus string                 `protobuf:"bytes,5,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"` // 分析状态
	EventId        string                 `protobuf:"bytes,6,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                      // 事件 ID（用于客户端幂等与回放）
	Version        int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`                                    // 聚合版本号
	OccurredAt     string                 `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`             // 事件发生时间（UTC RFC3339）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateVideoResponse) Reset() {
	*x = CreateVideoResponse{}
	mi := &file_api_video_v1_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoResponse) ProtoMessage() {}

func (x *CreateVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoResponse.ProtoReflect.Descriptor instead.
func (*CreateVideoResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{10}
}

func (x *CreateVideoResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *CreateVideoResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateVideoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateVideoResponse) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *CreateVideoResponse) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *CreateVideoResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateVideoResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CreateVideoResponse) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

// UpdateVideoRequest 表示对视频元数据的部分更新请求。
// 仅填充需要更新的字段，其余字段保持不变。
type UpdateVideoRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VideoId           string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`                                       // 视频 ID（必填）
	Title             *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`                                                    // 标题
	Description       *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`                                        // 描述
	Status            *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`                                                  // 视频状态
	MediaStatus       *string                `protobuf:"bytes,5,opt,name=media_status,json=mediaStatus,proto3,oneof" json:"media_status,omitempty"`                     // 媒体阶段状态
	AnalysisStatus    *string                `protobuf:"bytes,6,opt,name=analysis_status,json=analysisStatus,proto3,oneof" json:"analysis_status,omitempty"`            // 分析阶段状态
	DurationMicros    *int64                 `protobuf:"varint,7,opt,name=duration_micros,json=durationMicros,proto3,oneof" json:"duration_micros,omitempty"`           // 视频时长（微秒）
	ThumbnailUrl      *string                `protobuf:"bytes,8,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`                  // 缩略图 URL
	HlsMasterPlaylist *string                `protobuf:"bytes,9,opt,name=hls_master_playlist,json=hlsMasterPlaylist,proto3,oneof" json:"hls_master_playlist,omitempty"` // HLS 主清单
	Difficulty        *string                `protobuf:"bytes,10,opt,name=difficulty,proto3,oneof" json:"difficulty,omitempty"`                                         // 难度
	Summary           *string                `protobuf:"bytes,11,opt,name=summary,proto3,oneof" json:"summary,omitempty"`                                               // 摘要
	RawSubtitleUrl    *string                `protobuf:"bytes,12,opt,name=raw_subtitle_url,json=rawSubtitleUrl,proto3,oneof" json:"raw_subtitle_url,omitempty"`         // 原始字幕
	ErrorMessage      *string                `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`                 // 错误信息
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateVideoRequest) Reset() {
	*x = UpdateVideoRequest{}
	mi := &file_api_video_v1_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoRequest) ProtoMessage() {}

func (x *UpdateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoRequest.ProtoReflect.Descriptor instead.
func (*UpdateVideoRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UpdateVideoRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateVideoRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateVideoRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateVideoRequest) GetMediaStatus() string {
	if x != nil && x.MediaStatus != nil {
		return *x.MediaStatus
	}
	return ""
}

func (x *UpdateVideoRequest) GetAnalysisStatus() string {
	if x != nil && x.AnalysisStatus != nil {
		return *x.AnalysisStatus
	}
	return ""
}

func (x *UpdateVideoRequest) GetDurationMicros() int64 {
	if x != nil && x.DurationMicros != nil {
		return *x.DurationMicros
	}
	return 0
}

func (x *UpdateVideoRequest) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *UpdateVideoRequest) GetHlsMasterPlaylist() string {
	if x != nil && x.HlsMasterPlaylist != nil {
		return *x.HlsMasterPlaylist
	}
	return ""
}

func (x *UpdateVideoRequest) GetDifficulty() string {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return ""
}

func (x *UpdateVideoRequest) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *UpdateVideoRequest) GetRawSubtitleUrl() string {
	if x != nil && x.RawSubtitleUrl != nil {
		return *x.RawSubtitleUrl
	}
	return ""
}

func (x *UpdateVideoRequest) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// UpdateVideoResponse 返回更新后的核心字段与事件元数据。
type UpdateVideoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`                      // 视频 ID
	UpdatedAt      string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                // 更新时间（UTC RFC3339）
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                       // 视频状态
	MediaStatus    string                 `protobuf:"bytes,4,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`          // 媒体阶段状态
	AnalysisStatus string                 `protobuf:"bytes,5,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"` // 分析阶段状态
	EventId        string                 `protobuf:"bytes,6,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                      // 事件 ID
	Version        int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`                                    // 聚合版本号
	OccurredAt     string                 `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`             // 事件发生时间（UTC RFC3339）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateVideoResponse) Reset() {
	*x = UpdateVideoResponse{}
	mi := &file_api_video_v1_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoResponse) ProtoMessage() {}

func (x *UpdateVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoResponse.ProtoReflect.Descriptor instead.
func (*UpdateVideoResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateVideoResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UpdateVideoResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UpdateVideoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateVideoResponse) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *UpdateVideoResponse) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *UpdateVideoResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateVideoResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdateVideoResponse) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

// DeleteVideoRequest 表示删除视频的请求。
type DeleteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频 ID（必填）
	Reason        *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`            // 删除原因（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoRequest) Reset() {
	*x = DeleteVideoRequest{}
	mi := &file_api_video_v1_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoRequest) ProtoMessage() {}

func (x *DeleteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *DeleteVideoRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// DeleteVideoResponse 返回删除操作的事件元数据。
type DeleteVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`          // 被删除的视频 ID
	DeletedAt     string                 `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`    // 删除时间（UTC RFC3339）
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`          // 事件 ID
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`                        // 聚合版本号
	OccurredAt    string                 `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // 事件发生时间（UTC RFC3339）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoResponse) Reset() {
	*x = DeleteVideoResponse{}
	mi := &file_api_video_v1_video_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoResponse) ProtoMessage() {}

func (x *DeleteVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_video_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoResponse.ProtoReflect.Descriptor instead.
func (*DeleteVideoResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_video_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteVideoResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *DeleteVideoResponse) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *DeleteVideoResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeleteVideoResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeleteVideoResponse) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

var File_api_video_v1_video_proto protoreflect.FileDescriptor

const file_api_video_v1_video_proto_rawDesc = "" +
	"\n" +
	"\x18api/video/v1/video.proto\x12\bvideo.v1\x1a\x1bbuf/validate/validate.proto\"<\n" +
	"\x15GetVideoDetailRequest\x12#\n" +
	"\bvideo_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\avideoId\"G\n" +
	"\x16GetVideoDetailResponse\x12-\n" +
	"\x06detail\x18\x01 \x01(\v2\x15.video.v1.VideoDetailR\x06detail\"\xc5\x02\n" +
	"\vVideoDetail\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\x04 \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\x05 \x01(\tR\x0eanalysisStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\thas_liked\x18\b \x01(\bR\bhasLiked\x12%\n" +
	"\x0ehas_bookmarked\x18\t \x01(\bR\rhasBookmarked\x12\x1f\n" +
	"\vhas_watched\x18\n" +
	" \x01(\bR\n" +
	"hasWatched\"Y\n" +
	"\x1bListUserPublicVideosRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"w\n" +
	"\x1cListUserPublicVideosResponse\x12/\n" +
	"\x06videos\x18\x01 \x03(\v2\x17.video.v1.VideoListItemR\x06videos\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"w\n" +
	"\x14ListMyUploadsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12#\n" +
	"\rstatus_filter\x18\x03 \x03(\tR\fstatusFilter\"s\n" +
	"\x15ListMyUploadsResponse\x122\n" +
	"\x06videos\x18\x01 \x03(\v2\x1a.video.v1.MyUploadListItemR\x06videos\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xe2\x01\n" +
	"\rVideoListItem\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\x04 \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\x05 \x01(\tR\x0eanalysisStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xff\x01\n" +
	"\x10MyUploadListItem\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\x04 \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\x05 \x01(\tR\x0eanalysisStatus\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xd1\x01\n" +
	"\x12CreateVideoRequest\x12.\n" +
	"\x0eupload_user_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\fuploadUserId\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x125\n" +
	"\x12raw_file_reference\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x10rawFileReferenceB\x0e\n" +
	"\f_description\"\x89\x02\n" +
	"\x13CreateVideoResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\x04 \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\x05 \x01(\tR\x0eanalysisStatus\x12\x19\n" +
	"\bevent_id\x18\x06 \x01(\tR\aeventId\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x1f\n" +
	"\voccurred_at\x18\b \x01(\tR\n" +
	"occurredAt\"\xeb\x05\n" +
	"\x12UpdateVideoRequest\x12#\n" +
	"\bvideo_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\avideoId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x02R\x06status\x88\x01\x01\x12&\n" +
	"\fmedia_status\x18\x05 \x01(\tH\x03R\vmediaStatus\x88\x01\x01\x12,\n" +
	"\x0fanalysis_status\x18\x06 \x01(\tH\x04R\x0eanalysisStatus\x88\x01\x01\x125\n" +
	"\x0fduration_micros\x18\a \x01(\x03B\a\xbaH\x04\"\x02(\x00H\x05R\x0edurationMicros\x88\x01\x01\x12(\n" +
	"\rthumbnail_url\x18\b \x01(\tH\x06R\fthumbnailUrl\x88\x01\x01\x123\n" +
	"\x13hls_master_playlist\x18\t \x01(\tH\aR\x11hlsMasterPlaylist\x88\x01\x01\x12#\n" +
	"\n" +
	"difficulty\x18\n" +
	" \x01(\tH\bR\n" +
	"difficulty\x88\x01\x01\x12\x1d\n" +
	"\asummary\x18\v \x01(\tH\tR\asummary\x88\x01\x01\x12-\n" +
	"\x10raw_subtitle_url\x18\f \x01(\tH\n" +
	"R\x0erawSubtitleUrl\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\r \x01(\tH\vR\ferrorMessage\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_statusB\x0f\n" +
	"\r_media_statusB\x12\n" +
	"\x10_analysis_statusB\x12\n" +
	"\x10_duration_microsB\x10\n" +
	"\x0e_thumbnail_urlB\x16\n" +
	"\x14_hls_master_playlistB\r\n" +
	"\v_difficultyB\n" +
	"\n" +
	"\b_summaryB\x13\n" +
	"\x11_raw_subtitle_urlB\x10\n" +
	"\x0e_error_message\"\x89\x02\n" +
	"\x13UpdateVideoResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\x04 \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\x05 \x01(\tR\x0eanalysisStatus\x12\x19\n" +
	"\bevent_id\x18\x06 \x01(\tR\aeventId\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x1f\n" +
	"\voccurred_at\x18\b \x01(\tR\n" +
	"occurredAt\"a\n" +
	"\x12DeleteVideoRequest\x12#\n" +
	"\bvideo_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\avideoId\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"\xa5\x01\n" +
	"\x13DeleteVideoResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\tR\tdeletedAt\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1f\n" +
	"\voccurred_at\x18\x05 \x01(\tR\n" +
	"occurredAt2\xa1\x02\n" +
	"\x11VideoQueryService\x12S\n" +
	"\x0eGetVideoDetail\x12\x1f.video.v1.GetVideoDetailRequest\x1a .video.v1.GetVideoDetailResponse\x12e\n" +
	"\x14ListUserPublicVideos\x12%.video.v1.ListUserPublicVideosRequest\x1a&.video.v1.ListUserPublicVideosResponse\x12P\n" +
	"\rListMyUploads\x12\x1e.video.v1.ListMyUploadsRequest\x1a\x1f.video.v1.ListMyUploadsResponse2\xf9\x01\n" +
	"\x13VideoCommandService\x12J\n" +
	"\vCreateVideo\x12\x1c.video.v1.CreateVideoRequest\x1a\x1d.video.v1.CreateVideoResponse\x12J\n" +
	"\vUpdateVideo\x12\x1c.video.v1.UpdateVideoRequest\x1a\x1d.video.v1.UpdateVideoResponse\x12J\n" +
	"\vDeleteVideo\x12\x1c.video.v1.DeleteVideoRequest\x1a\x1d.video.v1.DeleteVideoResponseBDZBgithub.com/bionicotaku/lingo-services-catalog/api/video/v1;videov1b\x06proto3"

var (
	file_api_video_v1_video_proto_rawDescOnce sync.Once
	file_api_video_v1_video_proto_rawDescData []byte
)

func file_api_video_v1_video_proto_rawDescGZIP() []byte {
	file_api_video_v1_video_proto_rawDescOnce.Do(func() {
		file_api_video_v1_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_video_v1_video_proto_rawDesc), len(file_api_video_v1_video_proto_rawDesc)))
	})
	return file_api_video_v1_video_proto_rawDescData
}

var file_api_video_v1_video_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_video_v1_video_proto_goTypes = []any{
	(*GetVideoDetailRequest)(nil),        // 0: video.v1.GetVideoDetailRequest
	(*GetVideoDetailResponse)(nil),       // 1: video.v1.GetVideoDetailResponse
	(*VideoDetail)(nil),                  // 2: video.v1.VideoDetail
	(*ListUserPublicVideosRequest)(nil),  // 3: video.v1.ListUserPublicVideosRequest
	(*ListUserPublicVideosResponse)(nil), // 4: video.v1.ListUserPublicVideosResponse
	(*ListMyUploadsRequest)(nil),         // 5: video.v1.ListMyUploadsRequest
	(*ListMyUploadsResponse)(nil),        // 6: video.v1.ListMyUploadsResponse
	(*VideoListItem)(nil),                // 7: video.v1.VideoListItem
	(*MyUploadListItem)(nil),             // 8: video.v1.MyUploadListItem
	(*CreateVideoRequest)(nil),           // 9: video.v1.CreateVideoRequest
	(*CreateVideoResponse)(nil),          // 10: video.v1.CreateVideoResponse
	(*UpdateVideoRequest)(nil),           // 11: video.v1.UpdateVideoRequest
	(*UpdateVideoResponse)(nil),          // 12: video.v1.UpdateVideoResponse
	(*DeleteVideoRequest)(nil),           // 13: video.v1.DeleteVideoRequest
	(*DeleteVideoResponse)(nil),          // 14: video.v1.DeleteVideoResponse
}
var file_api_video_v1_video_proto_depIdxs = []int32{
	2,  // 0: video.v1.GetVideoDetailResponse.detail:type_name -> video.v1.VideoDetail
	7,  // 1: video.v1.ListUserPublicVideosResponse.videos:type_name -> video.v1.VideoListItem
	8,  // 2: video.v1.ListMyUploadsResponse.videos:type_name -> video.v1.MyUploadListItem
	0,  // 3: video.v1.VideoQueryService.GetVideoDetail:input_type -> video.v1.GetVideoDetailRequest
	3,  // 4: video.v1.VideoQueryService.ListUserPublicVideos:input_type -> video.v1.ListUserPublicVideosRequest
	5,  // 5: video.v1.VideoQueryService.ListMyUploads:input_type -> video.v1.ListMyUploadsRequest
	9,  // 6: video.v1.VideoCommandService.CreateVideo:input_type -> video.v1.CreateVideoRequest
	11, // 7: video.v1.VideoCommandService.UpdateVideo:input_type -> video.v1.UpdateVideoRequest
	13, // 8: video.v1.VideoCommandService.DeleteVideo:input_type -> video.v1.DeleteVideoRequest
	1,  // 9: video.v1.VideoQueryService.GetVideoDetail:output_type -> video.v1.GetVideoDetailResponse
	4,  // 10: video.v1.VideoQueryService.ListUserPublicVideos:output_type -> video.v1.ListUserPublicVideosResponse
	6,  // 11: video.v1.VideoQueryService.ListMyUploads:output_type -> video.v1.ListMyUploadsResponse
	10, // 12: video.v1.VideoCommandService.CreateVideo:output_type -> video.v1.CreateVideoResponse
	12, // 13: video.v1.VideoCommandService.UpdateVideo:output_type -> video.v1.UpdateVideoResponse
	14, // 14: video.v1.VideoCommandService.DeleteVideo:output_type -> video.v1.DeleteVideoResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_video_v1_video_proto_init() }
func file_api_video_v1_video_proto_init() {
	if File_api_video_v1_video_proto != nil {
		return
	}
	file_api_video_v1_video_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_video_v1_video_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_video_v1_video_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_video_v1_video_proto_rawDesc), len(file_api_video_v1_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_video_v1_video_proto_goTypes,
		DependencyIndexes: file_api_video_v1_video_proto_depIdxs,
		MessageInfos:      file_api_video_v1_video_proto_msgTypes,
	}.Build()
	File_api_video_v1_video_proto = out.File
	file_api_video_v1_video_proto_goTypes = nil
	file_api_video_v1_video_proto_depIdxs = nil
}
