// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/video/v1/video.proto

package videov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoQueryService_GetVideoDetail_FullMethodName = "/video.v1.VideoQueryService/GetVideoDetail"
)

// VideoQueryServiceClient is the client API for VideoQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VideoQueryService 提供视频只读查询能力。
type VideoQueryServiceClient interface {
	// GetVideoDetail 根据 video_id 返回视频元数据。
	GetVideoDetail(ctx context.Context, in *GetVideoDetailRequest, opts ...grpc.CallOption) (*GetVideoDetailResponse, error)
}

type videoQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoQueryServiceClient(cc grpc.ClientConnInterface) VideoQueryServiceClient {
	return &videoQueryServiceClient{cc}
}

func (c *videoQueryServiceClient) GetVideoDetail(ctx context.Context, in *GetVideoDetailRequest, opts ...grpc.CallOption) (*GetVideoDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVideoDetailResponse)
	err := c.cc.Invoke(ctx, VideoQueryService_GetVideoDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoQueryServiceServer is the server API for VideoQueryService service.
// All implementations must embed UnimplementedVideoQueryServiceServer
// for forward compatibility.
//
// VideoQueryService 提供视频只读查询能力。
type VideoQueryServiceServer interface {
	// GetVideoDetail 根据 video_id 返回视频元数据。
	GetVideoDetail(context.Context, *GetVideoDetailRequest) (*GetVideoDetailResponse, error)
	mustEmbedUnimplementedVideoQueryServiceServer()
}

// UnimplementedVideoQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoQueryServiceServer struct{}

func (UnimplementedVideoQueryServiceServer) GetVideoDetail(context.Context, *GetVideoDetailRequest) (*GetVideoDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoDetail not implemented")
}
func (UnimplementedVideoQueryServiceServer) mustEmbedUnimplementedVideoQueryServiceServer() {}
func (UnimplementedVideoQueryServiceServer) testEmbeddedByValue()                           {}

// UnsafeVideoQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoQueryServiceServer will
// result in compilation errors.
type UnsafeVideoQueryServiceServer interface {
	mustEmbedUnimplementedVideoQueryServiceServer()
}

func RegisterVideoQueryServiceServer(s grpc.ServiceRegistrar, srv VideoQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedVideoQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoQueryService_ServiceDesc, srv)
}

func _VideoQueryService_GetVideoDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoQueryServiceServer).GetVideoDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoQueryService_GetVideoDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoQueryServiceServer).GetVideoDetail(ctx, req.(*GetVideoDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoQueryService_ServiceDesc is the grpc.ServiceDesc for VideoQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.v1.VideoQueryService",
	HandlerType: (*VideoQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVideoDetail",
			Handler:    _VideoQueryService_GetVideoDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/video/v1/video.proto",
}

const (
	VideoCommandService_CreateVideo_FullMethodName = "/video.v1.VideoCommandService/CreateVideo"
	VideoCommandService_UpdateVideo_FullMethodName = "/video.v1.VideoCommandService/UpdateVideo"
	VideoCommandService_DeleteVideo_FullMethodName = "/video.v1.VideoCommandService/DeleteVideo"
)

// VideoCommandServiceClient is the client API for VideoCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VideoCommandService 提供视频写操作能力。
type VideoCommandServiceClient interface {
	// CreateVideo 创建新视频记录
	CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoResponse, error)
	// UpdateVideo 更新视频元数据
	UpdateVideo(ctx context.Context, in *UpdateVideoRequest, opts ...grpc.CallOption) (*UpdateVideoResponse, error)
	// DeleteVideo 删除视频记录
	DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*DeleteVideoResponse, error)
}

type videoCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoCommandServiceClient(cc grpc.ClientConnInterface) VideoCommandServiceClient {
	return &videoCommandServiceClient{cc}
}

func (c *videoCommandServiceClient) CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVideoResponse)
	err := c.cc.Invoke(ctx, VideoCommandService_CreateVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCommandServiceClient) UpdateVideo(ctx context.Context, in *UpdateVideoRequest, opts ...grpc.CallOption) (*UpdateVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVideoResponse)
	err := c.cc.Invoke(ctx, VideoCommandService_UpdateVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCommandServiceClient) DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*DeleteVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVideoResponse)
	err := c.cc.Invoke(ctx, VideoCommandService_DeleteVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoCommandServiceServer is the server API for VideoCommandService service.
// All implementations must embed UnimplementedVideoCommandServiceServer
// for forward compatibility.
//
// VideoCommandService 提供视频写操作能力。
type VideoCommandServiceServer interface {
	// CreateVideo 创建新视频记录
	CreateVideo(context.Context, *CreateVideoRequest) (*CreateVideoResponse, error)
	// UpdateVideo 更新视频元数据
	UpdateVideo(context.Context, *UpdateVideoRequest) (*UpdateVideoResponse, error)
	// DeleteVideo 删除视频记录
	DeleteVideo(context.Context, *DeleteVideoRequest) (*DeleteVideoResponse, error)
	mustEmbedUnimplementedVideoCommandServiceServer()
}

// UnimplementedVideoCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoCommandServiceServer struct{}

func (UnimplementedVideoCommandServiceServer) CreateVideo(context.Context, *CreateVideoRequest) (*CreateVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVideo not implemented")
}
func (UnimplementedVideoCommandServiceServer) UpdateVideo(context.Context, *UpdateVideoRequest) (*UpdateVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVideo not implemented")
}
func (UnimplementedVideoCommandServiceServer) DeleteVideo(context.Context, *DeleteVideoRequest) (*DeleteVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVideo not implemented")
}
func (UnimplementedVideoCommandServiceServer) mustEmbedUnimplementedVideoCommandServiceServer() {}
func (UnimplementedVideoCommandServiceServer) testEmbeddedByValue()                             {}

// UnsafeVideoCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoCommandServiceServer will
// result in compilation errors.
type UnsafeVideoCommandServiceServer interface {
	mustEmbedUnimplementedVideoCommandServiceServer()
}

func RegisterVideoCommandServiceServer(s grpc.ServiceRegistrar, srv VideoCommandServiceServer) {
	// If the following call pancis, it indicates UnimplementedVideoCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoCommandService_ServiceDesc, srv)
}

func _VideoCommandService_CreateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCommandServiceServer).CreateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCommandService_CreateVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCommandServiceServer).CreateVideo(ctx, req.(*CreateVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoCommandService_UpdateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCommandServiceServer).UpdateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCommandService_UpdateVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCommandServiceServer).UpdateVideo(ctx, req.(*UpdateVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoCommandService_DeleteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCommandServiceServer).DeleteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCommandService_DeleteVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCommandServiceServer).DeleteVideo(ctx, req.(*DeleteVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoCommandService_ServiceDesc is the grpc.ServiceDesc for VideoCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.v1.VideoCommandService",
	HandlerType: (*VideoCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVideo",
			Handler:    _VideoCommandService_CreateVideo_Handler,
		},
		{
			MethodName: "UpdateVideo",
			Handler:    _VideoCommandService_UpdateVideo_Handler,
		},
		{
			MethodName: "DeleteVideo",
			Handler:    _VideoCommandService_DeleteVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/video/v1/video.proto",
}
