// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bionicotaku/kratos-template/internal/clients"
	"github.com/bionicotaku/kratos-template/internal/conf"
	"github.com/bionicotaku/kratos-template/internal/controllers"
	"github.com/bionicotaku/kratos-template/internal/infrastructure/grpc_client"
	"github.com/bionicotaku/kratos-template/internal/infrastructure/grpc_server"
	"github.com/bionicotaku/kratos-template/internal/repositories"
	"github.com/bionicotaku/kratos-template/internal/services"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(server *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	greeterRepo := repositories.NewGreeterRepo(logger)
	clientConn, cleanup, err := grpcclient.NewGRPCClient(data, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRemote := clients.NewGreeterRemote(clientConn, logger)
	greeterUsecase := services.NewGreeterUsecase(greeterRepo, greeterRemote, logger)
	greeterHandler := controllers.NewGreeterHandler(greeterUsecase)
	grpcServer := grpcserver.NewGRPCServer(server, greeterHandler, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
