// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: internal/tasks/engagement/event.proto

package engagement

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	HasLiked      *bool                  `protobuf:"varint,3,opt,name=has_liked,json=hasLiked,proto3,oneof" json:"has_liked,omitempty"`
	HasBookmarked *bool                  `protobuf:"varint,4,opt,name=has_bookmarked,json=hasBookmarked,proto3,oneof" json:"has_bookmarked,omitempty"`
	HasWatched    *bool                  `protobuf:"varint,5,opt,name=has_watched,json=hasWatched,proto3,oneof" json:"has_watched,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventProto) Reset() {
	*x = EventProto{}
	mi := &file_internal_tasks_engagement_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProto) ProtoMessage() {}

func (x *EventProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tasks_engagement_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventProto.ProtoReflect.Descriptor instead.
func (*EventProto) Descriptor() ([]byte, []int) {
	return file_internal_tasks_engagement_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventProto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventProto) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *EventProto) GetHasLiked() bool {
	if x != nil && x.HasLiked != nil {
		return *x.HasLiked
	}
	return false
}

func (x *EventProto) GetHasBookmarked() bool {
	if x != nil && x.HasBookmarked != nil {
		return *x.HasBookmarked
	}
	return false
}

func (x *EventProto) GetHasWatched() bool {
	if x != nil && x.HasWatched != nil {
		return *x.HasWatched
	}
	return false
}

func (x *EventProto) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EventProto) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_internal_tasks_engagement_event_proto protoreflect.FileDescriptor

const file_internal_tasks_engagement_event_proto_rawDesc = "" +
	"\n" +
	"%internal/tasks/engagement/event.proto\x12\rengagement.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x02\n" +
	"\n" +
	"EventProto\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12 \n" +
	"\thas_liked\x18\x03 \x01(\bH\x00R\bhasLiked\x88\x01\x01\x12*\n" +
	"\x0ehas_bookmarked\x18\x04 \x01(\bH\x01R\rhasBookmarked\x88\x01\x01\x12$\n" +
	"\vhas_watched\x18\x05 \x01(\bH\x02R\n" +
	"hasWatched\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversionB\f\n" +
	"\n" +
	"_has_likedB\x11\n" +
	"\x0f_has_bookmarkedB\x0e\n" +
	"\f_has_watchedBTZRgithub.com/bionicotaku/lingo-services-catalog/internal/tasks/engagement;engagementb\x06proto3"

var (
	file_internal_tasks_engagement_event_proto_rawDescOnce sync.Once
	file_internal_tasks_engagement_event_proto_rawDescData []byte
)

func file_internal_tasks_engagement_event_proto_rawDescGZIP() []byte {
	file_internal_tasks_engagement_event_proto_rawDescOnce.Do(func() {
		file_internal_tasks_engagement_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_tasks_engagement_event_proto_rawDesc), len(file_internal_tasks_engagement_event_proto_rawDesc)))
	})
	return file_internal_tasks_engagement_event_proto_rawDescData
}

var file_internal_tasks_engagement_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_tasks_engagement_event_proto_goTypes = []any{
	(*EventProto)(nil),            // 0: engagement.v1.EventProto
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_internal_tasks_engagement_event_proto_depIdxs = []int32{
	1, // 0: engagement.v1.EventProto.occurred_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_tasks_engagement_event_proto_init() }
func file_internal_tasks_engagement_event_proto_init() {
	if File_internal_tasks_engagement_event_proto != nil {
		return
	}
	file_internal_tasks_engagement_event_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_tasks_engagement_event_proto_rawDesc), len(file_internal_tasks_engagement_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_tasks_engagement_event_proto_goTypes,
		DependencyIndexes: file_internal_tasks_engagement_event_proto_depIdxs,
		MessageInfos:      file_internal_tasks_engagement_event_proto_msgTypes,
	}.Build()
	File_internal_tasks_engagement_event_proto = out.File
	file_internal_tasks_engagement_event_proto_goTypes = nil
	file_internal_tasks_engagement_event_proto_depIdxs = nil
}
