// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video.sql

package catalogsql

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one

INSERT INTO catalog.videos (
    upload_user_id,
    created_at,
    updated_at,
    title,
    description,
    raw_file_reference,
    status,
    media_status,
    analysis_status
) VALUES (
    $1,
    now(),
    now(),
    $2,
    $4,
    $3,
    'pending_upload',
    'pending',
    'pending'
)
RETURNING
    video_id,
    upload_user_id,
    created_at,
    updated_at,
    title,
    description,
    raw_file_reference,
    status,
    media_status,
    analysis_status,
    raw_file_size,
    raw_resolution,
    raw_bitrate,
    duration_micros,
    encoded_resolution,
    encoded_bitrate,
    thumbnail_url,
    hls_master_playlist,
    difficulty,
    summary,
    tags,
    raw_subtitle_url,
    error_message
`

type CreateVideoParams struct {
	UploadUserID     uuid.UUID   `json:"upload_user_id"`
	Title            string      `json:"title"`
	RawFileReference string      `json:"raw_file_reference"`
	Description      pgtype.Text `json:"description"`
}

// Video 业务相关的 SQL 查询定义
// 由 sqlc 生成类型安全的 Go 代码
// 创建新视频记录，video_id 由数据库自动生成
func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (CatalogVideo, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.UploadUserID,
		arg.Title,
		arg.RawFileReference,
		arg.Description,
	)
	var i CatalogVideo
	err := row.Scan(
		&i.VideoID,
		&i.UploadUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.RawFileReference,
		&i.Status,
		&i.MediaStatus,
		&i.AnalysisStatus,
		&i.RawFileSize,
		&i.RawResolution,
		&i.RawBitrate,
		&i.DurationMicros,
		&i.EncodedResolution,
		&i.EncodedBitrate,
		&i.ThumbnailUrl,
		&i.HlsMasterPlaylist,
		&i.Difficulty,
		&i.Summary,
		&i.Tags,
		&i.RawSubtitleUrl,
		&i.ErrorMessage,
	)
	return i, err
}

const findVideoByID = `-- name: FindVideoByID :one
SELECT
    video_id,
    title,
    status,
    media_status,
    analysis_status,
    created_at,
    updated_at
FROM catalog.videos_ready_view
WHERE video_id = $1
`

// 根据 video_id 从只读视图查询视频详情（仅返回 ready/published 状态的视频）
func (q *Queries) FindVideoByID(ctx context.Context, videoID uuid.UUID) (CatalogVideosReadyView, error) {
	row := q.db.QueryRow(ctx, findVideoByID, videoID)
	var i CatalogVideosReadyView
	err := row.Scan(
		&i.VideoID,
		&i.Title,
		&i.Status,
		&i.MediaStatus,
		&i.AnalysisStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReadyVideosForTest = `-- name: ListReadyVideosForTest :many
SELECT
    video_id,
    title,
    status,
    media_status,
    analysis_status,
    created_at,
    updated_at
FROM catalog.videos_ready_view
ORDER BY created_at DESC
`

func (q *Queries) ListReadyVideosForTest(ctx context.Context) ([]CatalogVideosReadyView, error) {
	rows, err := q.db.Query(ctx, listReadyVideosForTest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogVideosReadyView{}
	for rows.Next() {
		var i CatalogVideosReadyView
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Status,
			&i.MediaStatus,
			&i.AnalysisStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
